version: '3'

services:

  mysql-local:
    platform: linux/x86_64
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=urlshortener
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Pass2021
    ports:
      - 3306:3306

  myapp-main:
    build:
      context: .
      dockerfile: Dockerfile
    image: urlshortener
    restart: on-failure
    ports:
      - 8080:8080